config/routes.rb
Rails.application.routes.draw do
  resources :quiz_questions
  resources :categories
  resources :quizzes
  devise_for :users
  
  root 'pages#home'

  get 'signup', to: 'users#new'
  get 'quizzes', to: 'quizzes#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :quizzes

  validates :name, presence: true, length: {minimum: 3, maximum: 50}, uniqueness: { case_sensitive: false }
  validates :desc, presence: true, length: {minimum: 3, maximum: 50}
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :quiz_quiestions, dependent: :destroy

  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/quiz_question.rb
class QuizQuestion < ApplicationRecord
  belongs_to :quiz 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    quizzes_path
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :desc)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

end

app/controllers/quiz_questions_controller.rb
class QuizQuestionsController < ApplicationController
  before_action :set_quiz_question, only: [:show, :edit, :update, :destroy]

  # GET /quiz_questions
  # GET /quiz_questions.json
  def index
    @quiz_questions = QuizQuestion.all
  end

  # GET /quiz_questions/1
  # GET /quiz_questions/1.json
  def show
  end

  # GET /quiz_questions/new
  def new
    @quiz_question = QuizQuestion.new
    @quizzes = Quiz.all.map{|q| [ q.title, q.id ] }
  end

  # GET /quiz_questions/1/edit
  def edit
    @quizzes = Quiz.all.map{|q| [ q.title, q.id ] }
    @quiz_question.quiz_id = params[:quiz_id]
  end

  # POST /quiz_questions
  # POST /quiz_questions.json
  def create
    @quiz_question = QuizQuestion.new(quiz_question_params)
    @quizzes = Quiz.all.map{|q| [ q.title, q.id ] }
    @quiz_question.quiz_id = params[:quiz_id]

    respond_to do |format|
      if @quiz_question.save

        format.html { redirect_to @quiz_question, notice: 'Quiz question was successfully created.' }
        format.json { render :show, status: :created, location: @quiz_question }
      else
        format.html { render :new }
        format.json { render json: @quiz_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quiz_questions/1
  # PATCH/PUT /quiz_questions/1.json
  def update
    @quiz_question = QuizQuestion.new(quiz_question_params)
    @quizzes = Quiz.all.map{|q| [ q.title, q.id ] }
    @quiz_question.quiz_id = params[:quiz_id]

    respond_to do |format|
      if @quiz_question.update(quiz_question_params)
        format.html { redirect_to @quiz_question, notice: 'Quiz question was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz_question }
      else
        format.html { render :edit }
        format.json { render json: @quiz_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quiz_questions/1
  # DELETE /quiz_questions/1.json
  def destroy
    @quiz_question.destroy
    respond_to do |format|
      format.html { redirect_to quiz_questions_url, notice: 'Quiz question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz_question
      @quiz_question = QuizQuestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_question_params
      params.fetch(:quiz_question, {}).permit(:correct_answer, :quiz_id, :description)
    end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:show, :edit, :update, :destroy]

  # GET /quizzes
  # GET /quizzes.json
  def index
    @quizzes = Quiz.all
  end

  # GET /quizzes/1
  # GET /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
    # @categories = Category.all
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # GET /quizzes/1/edit
  def edit
    # @categories = Category.all
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)
    @quiz.user = current_user
    @quiz.category_id = params[:category_id]

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to @quiz, notice: 'Quiz was successfully created.' }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1
  # PATCH/PUT /quizzes/1.json
  def update
    # @categories = Category.all
    @categories = Category.all.map{|c| [ c.name, c.id ] }
    @quiz.category_id = params[:category_id]


    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: 'Quiz was successfully updated.' }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1
  # DELETE /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: 'Quiz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quiz_params
      #params.fetch(:quiz, {})
      params.require(:quiz).permit(:title, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/quiz_questions_helper.rb
module QuizQuestionsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h1 class="text-center">New Category</h1>

  <div class="form-group">
    <div class="field">
      <%= f.text_field :name, class: "form-control col-md-8", placeholder: "Category Name", autofocus: true %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.text_area :desc, class: "form-control col-md-8", placeholder: "Category Description (Desc)", autofocus: true  %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-light btn-category-new' %>
  </div>

  <%= link_to 'All Categories', categories_path %>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="categories-list">
  <div class="container">

    <h1 class="text-center">All Categories</h1>

    <div class="row">
      <% @categories.each do |category| %>
        <div class="card text-white bg-dark text-center" style="max-width: 18rem;">
          <div class="card-header text-center">
            <%= link_to "#{category.name}", category_path(category) %>
          </div>
          <div class="card-body ">
            <p class="card-text text-center"><%= category.desc %></p>
          </div>
          <div class="card-footer">
            <p class="card-text text-center">
              <small><%= pluralize(category.quizzes.count, "quiz") %></small>
            </p>

            <% if user_signed_in? && (current_user)%>
              <div class="category-actions">
                <div class="btn btn-group">
                  <%= link_to 'Edit', edit_category_path(category), class: "btn btn-primary btn-md" %>
                  <%= link_to 'Delete', category, class: "btn btn-danger btn-md", method: :delete, data: { confirm: 'Are you sure?' } %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <!-- <%= link_to 'New Category', new_category_path %> -->

  </div>
</div>

app/views/categories/new.html.erb
<div class="category-form">
  <div class="container">

    <%= render 'form', category: @category %>

  </div>
</div>

app/views/categories/show.html.erb
<div class="show-category">
  <div class="container">

    <!-- <p id="notice"><%= notice %></p> -->

    <div class="card bg-light mb-3" style="max-width: 18rem;">
      <div class="card-header"><%= @category.name %></div>
      <div class="card-body ">
        <h5 class="card-title"></h5>
        <p class="card-text"><%= @category.desc %></p>
      </div>
      <div class="card-footer bg-transparent border-light">
        <%= link_to 'Edit', edit_category_path(@category) %> |
        <%= link_to 'Back', categories_path %>
      </div>
    </div>



  </div>
</div>

app/views/layouts/_footer.erb
<!-- Footer -->
<footer class="page-footer font-small">
  <div class="container-fluid py-3">
    <div class="row">
      <div class="media-icons col-md-12">
        <div class="text-center">
          <!-- GitHub -->
          <a href="https://github.com/hatanasova?tab=repositories" class="git-ic">
            <i class="fab fa-github fa-lg white-text fa-fw fa-2x"></i>
          </a>
          <!-- Twitter -->
          <a href="https://twitter.com/" class="tw-ic">
            <i class="fab fa-twitter fa-lg white-text fa-fw fa-2x"></i>
          </a>
          <!--Linkedin -->
          <a href="https://www.linkedin.com/in/hatanasova/" class="li-ic">
            <i class="fab fa-linkedin-in fa-lg white-text fa-fw fa-2x"></i>
          </a>
          <!--Instagram-->
          <a href="https://www.instagram.com/h_atanasova/" class="ins-ic">
            <i class="fab fa-instagram fa-lg white-text fa-fw fa-2x"></i>
          </a>
        </div>
      </div>
    </div>
  </div>
  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">&copy <%= Time.zone.now.year %> Copyright:
    <a class="copyright"> Hristina Atanasova</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_navigation.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top"> <!-- add  class -->
  <%= link_to "QuizApp", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto pull-left">
      <!-- <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li> -->

      <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          User Settings
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <!-- <a class="dropdown-item" href="#">Action</a> -->
          <%= link_to 'New Quiz', new_quiz_path, class: 'dropdown-item' %>
          <%= link_to 'New Category', new_category_path, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <%= link_to 'Edit Profile', edit_user_registration_path, class: 'dropdown-item' %>
          <%= link_to 'Sign Out', destroy_user_session_path, class: 'dropdown-item', method: :delete %>
        </div>
      </li>
      <% end %>

      <!-- Redirect to all Quizzes  -->
      <li class="nav-item active">
        <%= link_to 'All Quizzes', quizzes_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to 'All Categories', categories_path, class: 'nav-link' %>
      </li>
      <li class="nav-item active">
        <%= link_to 'Questions', quiz_questions_path, class: 'nav-link' %>
      </li>
    </ul>

    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuizApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Welcome to the QuizApp</h1>

    <div class="col-md-12">
      <div class="text-center">
        <!-- <button type="button" class="btn btn-outline-light btn-lg">Log In</button> -->
        <% if !user_signed_in? %>
          <%= link_to "Log In", user_session_path, class: "btn btn-outline-light btn-lg" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-light btn-lg" %>
        <% end %>
      </div>
    </div>

  </div>
</div>

<div class="container-fluid">
  <div class="row">
    <div class="text-center">

      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="https://www.ccjays.com/wp-content/uploads/2019/01/1969/always-up-to-date-guide-to-social-media-image-sizes.png" alt="Card image cap">
        <div class="card-body">
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
      </div>

      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="https://www.ccjays.com/wp-content/uploads/2019/01/1969/always-up-to-date-guide-to-social-media-image-sizes.png" alt="Card image cap">
        <div class="card-body">
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
      </div>

      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="https://www.ccjays.com/wp-content/uploads/2019/01/1969/always-up-to-date-guide-to-social-media-image-sizes.png" alt="Card image cap">
        <div class="card-body">
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
      </div>

      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="https://www.ccjays.com/wp-content/uploads/2019/01/1969/always-up-to-date-guide-to-social-media-image-sizes.png" alt="Card image cap">
        <div class="card-body">
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/quiz_questions/_form.html.erb
<div class="quiz_question">
  <div class="container">
    <%= form_with(model: quiz_question, local: true) do |f| %>
      <% if quiz_question.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(quiz_question.errors.count, "error") %>
            prohibited this quiz_question from being saved:</h2>

          <ul>
            <% quiz_question.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <!-- <div class="form-group">
        <div class="field">
          <%= f.label :question, "Question" %>
          <%= f.text_field :name, class: "form-control col-md-8", placeholder: "Question Description", autofocus: true %>
        </div>
      </div> -->
      <h1 class="text-center">Quiz Question</h1>

      <div class="form-group">
        <div class="field">
          <%= f.label :description,  'Question Description', :class => 'control-label' %>
          <%= f.text_area :description, rows: 7, class: "form-control col-md-8", placeholder: "Describe the quiestion...", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="field">
          <%= f.radio_button :correct_answer, true %>
          <%= f.label :correct_answer, "Correct" %>
        </div>
      </div>

      <div class="form-group">
        <div class="field">
          <%= f.radio_button :correct_answer, false %>
          <%= f.label :correct_answer, "Incorrect" %>
        </div>
      </div>

      <div class="dropdown btn text-center" style="background-color: #fff; margin: 0;">
        <%= select_tag(:quiz_id, options_for_select(@quizzes), :prompt => "Select Quiz", class: "dropdown-item btn-dropdown btn btn-light btn-category") %>
      </div>

      <div class="actions">
        <%= f.submit class: "btn btn-light btn-md"%> <br>
      <%= link_to 'Go Back to Quizzes', quizzes_path, class: "btn btn-outline-light btn-md" %>
      </div>
    <% end %>

  </div>
</div>

app/views/quiz_questions/edit.html.erb
<%= render 'form', quiz_question: @quiz_question %>

<!-- <%= link_to 'Show', @quiz_question %> |
<%= link_to 'Back', quiz_questions_path %> -->

app/views/quiz_questions/index.html.erb
<div class="show-quiz_questions">
  <div class="container">

      <h1 class="text-center">Quiz Questions</h1>

      <div class="row">
        <% @quiz_questions.each do |quiz_question| %>
        <div class="card text-white bg-dark text-center" style="max-width: 18rem;">
          <div class="card-header text-center">
            <%= "#{quiz_question.description}" %>
          </div>
          <div class="card-body">
            <p class="card-text text-center"><%= "ID: #{quiz_question.id}" %></p>
          </div>
          <div class="card-footer">
            <div class="btn btn-group">
              <%= link_to 'Show', quiz_question, class: "btn btn-info btn-sm" %>
              <%= link_to 'Edit', edit_quiz_question_path(quiz_question), class: "btn btn-primary btn-sm" %>
              <%= link_to 'Destroy', quiz_question, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
          </div>
          </div>
        </div>
        <% end %>
      </div>

      <%= link_to 'New Quiz Question', new_quiz_question_path %>

  </div>
</div>

app/views/quiz_questions/new.html.erb
<%= render 'form', quiz_question: @quiz_question %>

<!-- <%= link_to 'Back', quiz_questions_path %> -->

app/views/quiz_questions/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card bg-light mb-3" style="max-width: 18rem;">
  <div class="card-header"><%= @quiz_question.description %></div>

  <div class="card-body ">
    <%= @quiz_question.correct_answer %>
  </div>

  <div class="card-footer bg-transparent border-light">
    <%= %>
    <%= %>
  </div>
</div>

<%= link_to 'Edit', edit_quiz_question_path(@quiz_question) %> |
<%= link_to 'Back', quiz_questions_path %>

app/views/quizzes/_form.html.erb
<div class="quiz-form">
  <div class="container">
    <% if quiz.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

        <ul>
          <% quiz.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <h1 class="text-center">New Quiz</h1>

    <div class="col-md-12">
      <%= form_with(model: quiz, local: true) do |f| %>

      <div class="form-group">
        <div class="field">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control col-md-8", placeholder: "Quiz title", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="field">
          <%= f.label :description %>
          <%= f.text_area :description, rows: 7, class: "form-control col-md-8", placeholder: "Quiz description", autofocus: true %>
        </div>
      </div>

      <div class="dropdown btn text-center" style="background-color: #fff; margin: 0;">
        <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select Category", class: "dropdown-item btn-dropdown btn btn-light btn-category") %>
      </div>

      <div class="actions">
        <%= f.submit class: "btn btn-light btn-md"%> <br>
        <%= link_to 'Go Back to Quizzes', quizzes_path, class: "btn btn-outline-light btn-md" %>
      </div>
      <% end %>
    </div>

  </div>
</div>

app/views/quizzes/edit.html.erb
<%= render 'form', quiz: @quiz %>

<!--
<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>
-->

app/views/quizzes/index.html.erb
<div class="show-quizzes">
  <div class="container">

    <h1 class="text-center">All Quizzes</h1>

    <div class="row">
      <% @quizzes.each do |quiz| %>
        <div class="card text-white bg-dark text-center" style="max-width: 18rem;">
          <div class="card-header text-center">
            <%= link_to quiz.title, quiz_path(quiz) %>
          </div>
          <div class="card-body ">
            <p class="card-text text-center"><%= truncate(quiz.description, length: 100) %></p>
          </div>
          <div class="card-footer">
            <p class="card-text text-center">
              <small><%= simple_format("Category: " + quiz.category.name) %></small>
            </p>

            <% if user_signed_in? && (current_user == quiz.user)%>
              <div class="actions">
                <div class="btn btn-group">
                  <%= link_to 'Edit', edit_quiz_path(quiz), class: "btn btn-primary btn-md" %>
                  <%= link_to 'Delete', quiz, class: "btn btn-danger btn-md", method: :delete, data: { confirm: 'Are you sure?' } %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    <!-- <% if user_signed_in? %> <div class="col-md-8"> <%= link_to 'New Quiz', new_quiz_path, class: "btn btn-info btn-lg" %> </div> <% end %> -->

  </div>
</div>

app/views/quizzes/new.html.erb
<%= render 'form', quiz: @quiz %>

app/views/quizzes/show.html.erb
<div class="show-quiz">
  <div class="container">

    <!-- <p id="notice"><%= notice %></p> -->

    <!-- <%= simple_format(@quiz.title) %>
    <%= simple_format(@quiz.description) %>

    <div class="show_category">Category:
      <%= simple_format(@quiz.category.name) %>
    </div>

    <%= link_to 'Edit', edit_quiz_path(@quiz) %> |
    <%= link_to 'Back', quizzes_path %> -->

    <div class="card bg-light mb-3" style="max-width: 18rem;">
      <div class="card-header"><%= simple_format(@quiz.title) %></div>
      <div class="card-body ">
        <h5 class="card-title"></h5>
        <p class="card-text"><%= simple_format(@quiz.category.name) %></p>
      </div>
      <div class="card-footer bg-transparent border-light">
        <%= link_to 'Edit', edit_quiz_path(@quiz) %>
        <%= link_to 'Back', quizzes_path %>
      </div>
    </div>

  </div>
</div>